development:
  adapter: postgresql
  encoding: unicode
  database: rental1_db
  pool: 5
  username: acer
  password: postgres

  
test:
  adapter: postgresql
  encoding: unicode
  database: rental1_test_db
  pool: 5
  username: acer
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: rental1_pro_db
  pool: 5
  username: acer
  password: postgres